name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ms-Njuguna
          template: classic
          base: header, repositories
          config_timezone: Africa/Nairobi
          
          # Private Contributions & Indepth Analysis
          repositories_batch: 200
          plugin_languages: yes
          plugin_languages_indepth: yes # Analyzes your files to detect React, Django, etc.
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          
          # Remove boilerplate languages to keep it recruiter-ready
          plugin_languages_ignored: html, css, scss
          
          # Activity heat map
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Activity Plugin: Shows you are active and consistent
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
